name: "Immich Kiosk"
version: "latest"
slug: "immich_kiosk"
description: "Live slideshow van een Immich-album (bv. voor een feestje) op een TV/scherm"
url: "https://github.com/damongolding/immich-kiosk"
arch:
  - aarch64
  - amd64
  - armv7
image: "ghcr.io/damongolding/immich-kiosk"
startup: application
boot: auto
init: false
host_network: false
ports:
  "3000/tcp": 3000
ports_description:
  "3000/tcp": "Kiosk web UI"
environment:
  KIOSK_IMMICH_URL: "http://192.168.1.60:8181"
  KIOSK_IMMICH_API_KEY: "dXGZygEOS1dq9e1QfvZ6ILfkwNwToapXBadktaExc"
  KIOSK_ALBUMS: "c7251e10-8dcc-42ba-a35a-4dbca65fc865"
  KIOSK_DURATION: "8"
  KIOSK_FETCHED_ASSETS_SIZE: "200"
  KIOSK_CACHE: "true"
  KIOSK_PREFETCH: "true"
  KIOSK_SHOW_TIME: "false"
